"""add_v02_tables

Revision ID: 2dd3344558db
Revises: 001
Create Date: 2026-01-20 14:47:14.900379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd3344558db'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_key', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('reference_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_user_key'), 'credit_transactions', ['user_key'], unique=False)
    op.create_table('daily_streaks',
    sa.Column('user_key', sa.String(length=80), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('total_days', sa.Integer(), nullable=True),
    sa.Column('last_read_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_key')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_key', sa.String(length=80), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('credits_per_month', sa.Integer(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_key'), 'subscriptions', ['user_key'], unique=False)
    op.create_table('user_credits',
    sa.Column('user_key', sa.String(length=80), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('total_purchased', sa.Integer(), nullable=True),
    sa.Column('total_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_key')
    )
    op.create_table('daily_stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('theme', sa.String(length=30), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('book_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_stories_date'), 'daily_stories', ['date'], unique=False)
    op.create_table('reading_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_key', sa.String(length=80), nullable=False),
    sa.Column('book_id', sa.String(length=60), nullable=False),
    sa.Column('read_date', sa.DateTime(), nullable=False),
    sa.Column('reading_time', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_logs_user_key'), 'reading_logs', ['user_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_logs_user_key'), table_name='reading_logs')
    op.drop_table('reading_logs')
    op.drop_index(op.f('ix_daily_stories_date'), table_name='daily_stories')
    op.drop_table('daily_stories')
    op.drop_table('user_credits')
    op.drop_index(op.f('ix_subscriptions_user_key'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('daily_streaks')
    op.drop_index(op.f('ix_credit_transactions_user_key'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    # ### end Alembic commands ###
